services:
  - type: web
    name: mnemonic‑pizza‑app
    env: python
    plan: free

    # make sure Python can import tonysdonair/
    envVars:
      - key: PYTHONPATH
        value: "./"

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tonysdonair.app:app
